name: 'Hello world Docker Action'
description: 'Say Hello to a user or the World'
inputs:
  Who-to-great:
    description: 'Who to great'
    required: true
    default: 'world'
outputs: 
  time: 
  description: 'The time to say hello'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-great }}
